# Generated by Django 3.0.7 on 2020-06-23 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'materials',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Countries')),
                ('materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Materials')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0, unique=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_app.Categories')),
            ],
            options={
                'db_table': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='ProductsWColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('product_number', models.IntegerField(unique=True)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Colors')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Products')),
            ],
            options={
                'db_table': 'productswcolors',
            },
        ),
        migrations.CreateModel(
            name='ProductSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_w_colors', models.ManyToManyField(to='product_app.ProductsWColors')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Sizes')),
            ],
            options={
                'db_table': 'product_sizes',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.SubCategories'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=1000)),
                ('products_w_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductsWColors')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='colors',
            name='products',
            field=models.ManyToManyField(through='product_app.ProductsWColors', to='product_app.Products'),
        ),
        migrations.AddField(
            model_name='categories',
            name='menus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Menus'),
        ),
    ]
