# Generated by Django 3.0.7 on 2020-06-23 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductsWColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('product_number', models.IntegerField(unique=True)),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Colors')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Products')),
            ],
            options={
                'db_table': 'productswcolors',
            },
        ),
        migrations.AddField(
            model_name='colors',
            name='products',
            field=models.ManyToManyField(through='product_app.ProductsWColors', to='product_app.Products'),
        ),
    ]
