# Generated by Django 3.1a1 on 2020-06-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='menus',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='subcategories',
            table='subcategories',
        ),
    ]
