# Generated by Django 3.0.7 on 2020-06-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img_url',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.Categories'),
        ),
    ]
