# Generated by Django 3.0.7 on 2020-07-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.ProductColor'),
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.ProductColor'),
        ),
        migrations.AddField(
            model_name='productcolorsize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Size'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Color'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='user',
            field=models.ManyToManyField(through='product_app.Review', to='users.User'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Country'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='menu_category_subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.MenuCategorySubCategory'),
        ),
        migrations.AddField(
            model_name='menucategorysubcategory',
            name='menu_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.MenuCategory'),
        ),
        migrations.AddField(
            model_name='menucategorysubcategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.SubCategory'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Category'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.Menu'),
        ),
        migrations.AddField(
            model_name='detailimage',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_app.ProductColor'),
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(through='product_app.ProductColor', to='product_app.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ManyToManyField(through='product_app.MenuCategory', to='product_app.Menu'),
        ),
    ]
