# Generated by Django 3.0.7 on 2020-06-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductThumnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('products_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductColor')),
            ],
        ),
        migrations.CreateModel(
            name='Reveiw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000)),
                ('products_colosr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductColor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductcolorProductthumnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_thumnails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductThumnail')),
                ('products_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductColor')),
            ],
        ),
        migrations.CreateModel(
            name='ListThumnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=1000)),
                ('products_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductColor')),
            ],
        ),
    ]
