# Generated by Django 3.0.7 on 2020-07-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_app', '0001_initial'),
        ('users', '0001_initial'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_color',
            field=models.ManyToManyField(through='cart_app.Cart', to='product_app.ProductColor'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart_app.Order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.ProductColor'),
        ),
    ]
